---
title: "ST-515 (A) Practical Sheet"
author: "Manoj C. Patil"
date: "`r Sys.Date()`"
output: word_document
---


## Practical Sheet (B8)

**Topic: Analysis of single replicate of two-level factorial designs**

1. A chemical product is produced in pressure vessel. A factorial experiment is carried with four factors as temperature (A), pressure (B), concentration (C) and stirring rate (D) each at two levels. The response data from the single replicate of experiment is as follows.

| Run label | (1) | a | b | ab | c | ac | bc | abc | d | ad | bd | abd | cd | acd | bcd | abcd |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
|  | 45 | 71 | 48 | 65 | 68 | 60 | 80 | 65 | 43 | 100 | 45 | 104 | 75 | 86 | 70 | 96 |

i. Estimate all the 15 factorial effects.
j. Obtain the main effect and interaction plots for all the treatment combinations.
k. Obtain the normal probability plots of the effects and identify the significant effects from it.
l. Construct an ANOVA with the significant effects identified from normal probability plot in (iii).

2. An experiment was run in a semiconductor fabrication plant in an effort to increase yield. Five factors each at two levels were studied. The unreplicated 2^5 design shown below was run.

| Run label | (1) | a | b | ab | c | ac | bc | abc | d | ad | bd | abd | cd | acd | bcd | abcd |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
|  | 7 | 9 | 34 | 55 | 16 | 20 | 40 | 60 | 8 | 10 | 32 | 50 | 18 | 21 | 44 | 61 |
|  | 8 | 12 | 35 | 52 | 15 | 55 | 45 | 65 | 6 | 10 | 30 | 53 | 15 | 20 | 41 | 63 |

i. Construct the normal probability plot of the effect estimates. Which effects appear to be large?
j. Construct an ANOVA with the significant effects identified from normal probability plot in (ii).
k. Assuming that all 4-factor and 5-factor interactions to be negligible analyze the data.
l. Obtain the main effect and interaction plots for all the treatment combinations.
