---
title: "ST-515 (A) Practical Sheet"
author: "Manoj C. Patil"
date: "`r Sys.Date()`"
output: word_document
---


## Practical Sheet (B9)

**Topic: Analysis of response surface models**

1. The effective life of tool installed a numerically controlled machine is thought to be affected the cutting speed and tool angle. Three speeds and three angles are selected and two replicates of factorial experiment are run. The data from this experiment is as follows.

| Tool angle (in degrees) | Cutting speed 125 (inches/min) | Cutting speed 150 (inches/min) | Cutting speed 175 (inches/min) |
| --- | --- | --- | --- |
| 15 | -1, -1 | -3, 0 | 2, 3 |
| 20 | 0, 2 | 1, 3 | 4, 6 |
| 25 | -1, 0 | 5, 6 | 0, -1 |

i. Fit the second order response surface model to the above data.
j. Obtain response surface graph for tool life.
k. Obtain contour plot for tool life at -1.8, -0.6, 0.5, 1.7, 2.3, 4.0, 5.1, 3.

2. Consider the following fitted response surface for predicting response for given predictor variables x1 and x2 with their range of variation in experiment as (15 to 25) and (125 to 175) respectively.

Obtain response surface graph for the above fitted response. Also obtain contour plot for tool life at -1.7, -0.6, 0.4, 1.9, 2.3, 3.2, 4.0, 4.5, 5.1, 3.

3. Consider the following data.

|  |  |  |  |  |  |  |  |
| --- | --- | --- | --- | --- | --- | --- | --- |
| y | 262 | 4175 | 160 | 1635 | 6210 | 2630 | 7071 |
| x1 | 1.0 | 1.0 | 1.5 | 1.5 | 0.5 | 1.0 | 0.5 |
| x2 | 1.0 | 4.0 | 4.0 | 2.0 | 5.0 | 1.5 | 2.5 |

i. Fit the second order response surface model to the above data.
j. Obtain graph of the fitted response surface model and sketch the contour plots at.
k. Obtain the predicted value of response at x1=1.2, x2=2.0 and x1=1.0, x2=3.0.
